// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "wechat-backend/service/user/api/internal/handler/user"
	"wechat-backend/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyAuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: user.DetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friends",
					Handler: user.FriendListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/grouplist",
					Handler: user.GroupListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groupcrew",
					Handler: user.GroupCrewHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/groupdetail",
					Handler: user.GroupDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/user"),
	)
}
