// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentsFieldNames          = builder.RawFieldNames(&Comments{})
	commentsRows                = strings.Join(commentsFieldNames, ",")
	commentsRowsExpectAutoSet   = strings.Join(stringx.Remove(commentsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	commentsRowsWithPlaceHolder = strings.Join(stringx.Remove(commentsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	commentsModel interface {
		Insert(ctx context.Context, data *Comments) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Comments, error)
		Update(ctx context.Context, data *Comments) error
		Delete(ctx context.Context, id int64) error
		SelectCommentList(ctx context.Context, tid string) ([]*CommentDetail, error)
	}

	defaultCommentsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Comments struct {
		Id         int64     `db:"id"`        // id
		Cid        string    `db:"cid"`       // 评论编号id
		ParentId   string    `db:"parent_id"` //  父级评论id   0代表评论说说
		Uid        int64     `db:"uid"`       // 发表评论的用户
		Tid        string    `db:"tid"`       // 文章id
		Content    string    `db:"content"`
		CreateTime time.Time `db:"create_time"` // 评论时间
	}
)

func newCommentsModel(conn sqlx.SqlConn) *defaultCommentsModel {
	return &defaultCommentsModel{
		conn:  conn,
		table: "`comments`",
	}
}

func (m *defaultCommentsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCommentsModel) SelectCommentList(ctx context.Context, tid string) ([]*CommentDetail, error) {
	query := "select c.cid, c.parent_id, u.uid, u.username, c.content, c.create_time FROM `comments` as c " +
		"join `users` as u on c.uid = u.uid where tid = ? order by create_time asc"
	var resp []*CommentDetail
	err := m.conn.QueryRowCtx(ctx, &resp, query, tid)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentsModel) FindOne(ctx context.Context, id int64) (*Comments, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", commentsRows, m.table)
	var resp Comments
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentsModel) Insert(ctx context.Context, data *Comments) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, commentsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Cid, data.ParentId, data.Uid, data.Tid, data.Content)
	return ret, err
}

func (m *defaultCommentsModel) Update(ctx context.Context, data *Comments) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Cid, data.ParentId, data.Uid, data.Tid, data.Content, data.Id)
	return err
}

func (m *defaultCommentsModel) tableName() string {
	return m.table
}
