// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package userclient

import (
	"context"

	"wechat-backend/service/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty           = user.Empty
	UIdListResponse = user.UIdListResponse

	User interface {
		GetAllUserIdList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UIdListResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetAllUserIdList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UIdListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetAllUserIdList(ctx, in, opts...)
}
