// Code generated by goctl. DO NOT EDIT!
// Source: service.proto

package server

import (
	"context"

	"go-back/user/rpc/internal/logic"
	"go-back/user/rpc/internal/svc"
	"go-back/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetGroupIdList(ctx context.Context, in *user.UidRequest) (*user.GroupIdListResponse, error) {
	l := logic.NewGetGroupIdListLogic(ctx, s.svcCtx)
	return l.GetGroupIdList(in)
}
