// Code generated by goctl. DO NOT EDIT.
package types

type PublishRequest struct {
	Uid     int64  `json:"uid"`
	Content string `json:"content"`
	Imgs    string `json:"imgs"`
	State   int64  `json:"state"`
}

type LiskeRequest struct {
	Uid int64  `json:"uid"`
	Tid string `json:"tid"`
}

type EmptyResponse struct {
}

type CommentRequest struct {
	ParentId string `json:"parentid"`
	Uid      int64  `json:"uid"`
	Tid      string `json:"tid"`
	Content  string `json:"content"`
}

type GetCommentListRequest struct {
	Tid string `form:"tid"`
}

type CommentDetail struct {
	Cid              string          `json:"cid"`
	ParentId         string          `json:"parentid"`
	Uid              int64           `json:"uid"`
	Username         string          `json:"username"`
	Content          string          `json:"content"`
	CreateTime       string          `json:"create_time"`
	ChildCommentList []CommentDetail `json:"childcommentlist"`
}

type GetCommentListResponse struct {
	CommentList []CommentDetail `json:"commentlist"`
}

type GetTalkListRequest struct {
	Uid int64 `form:"uid"`
}

type TalkListDetail struct {
	Tid        string `json:"tid"`
	Uid        int64  `json:"uid"`
	Username   string `json:"username"`
	Content    string `json:"content"`
	Imgs       string `json:"imgs"`
	State      int64  `json:"state"`
	CreateTime string `json:"create_time"`
	UpdateTime string `json:"update_time"`
}

type GetTalkListResponse struct {
	TalkList []TalkListDetail `json:"talklist"`
}
