// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupsFieldNames          = builder.RawFieldNames(&Groups{})
	groupsRows                = strings.Join(groupsFieldNames, ",")
	groupsRowsExpectAutoSet   = strings.Join(stringx.Remove(groupsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	groupsRowsWithPlaceHolder = strings.Join(stringx.Remove(groupsFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
)

type (
	groupsModel interface {
		Insert(ctx context.Context, data *Groups) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Groups, error)
		Update(ctx context.Context, data *Groups) error
		Delete(ctx context.Context, id int64) error
		GroupListByUid(ctx context.Context, uid int64) ([]*GroupInfoDto, error)
		GroupByGid(ctx context.Context, uid int64) (*GroupDetailDto, error)
	}

	defaultGroupsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Groups struct {
		Id         int64  `db:"id"`          // id
		Gid        int64  `db:"gid"`         // 群聊id 雪花算法
		Uid        int64  `db:"uid"`         // 用户id 创建者
		Gname      string `db:"gname"`       // 群聊名称
		Avatar     string `db:"avatar"`      // 群聊头像
		Count      uint64 `db:"count"`       // 人数 通过触发器维护
		CreateTime string `db:"create_time"` // 创建时间
		UpdateTime string `db:"update_time"` // 更新时间
	}
)

func newGroupsModel(conn sqlx.SqlConn) *defaultGroupsModel {
	return &defaultGroupsModel{
		conn:  conn,
		table: "`groups`",
	}
}

func (m *defaultGroupsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultGroupsModel) GroupListByUid(ctx context.Context, uid int64) ([]*GroupInfoDto, error) {
	query := fmt.Sprintf("select g.gid,g.uid,g.gname, g.avatar,g.count,g.create_time from %s as g where gid in (select gid from `groupfriends` where `uid` = ?)", m.table)
	var resp []*GroupInfoDto
	//err := m.conn.QueryRowCtx(ctx, &resp, query, uid)
	err := m.conn.QueryRows(&resp, query, uid)
	if err != nil {
		return nil, err
	}
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultGroupsModel) GroupByGid(ctx context.Context, id int64) (*GroupDetailDto, error) {
	//query := fmt.Sprintf("select gid,uid,gname, avatar,count,create_time from %s where `gid` = ?", m.table)
	query := fmt.Sprintf("select g.gid,g.uid,g.gname, g.avatar,g.count,g.create_time ,u.nickname from %s as g join `users` as u on g.uid = u.uid where `gid` = ?", m.table)
	var resp GroupDetailDto
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) FindOne(ctx context.Context, id int64) (*Groups, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", groupsRows, m.table)
	var resp Groups
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultGroupsModel) Insert(ctx context.Context, data *Groups) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, groupsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Gid, data.Uid, data.Gname, data.Avatar, data.Count)
	return ret, err
}

func (m *defaultGroupsModel) Update(ctx context.Context, data *Groups) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, groupsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Gid, data.Uid, data.Gname, data.Avatar, data.Count, data.Id)
	return err
}

func (m *defaultGroupsModel) tableName() string {
	return m.table
}
