// Code generated by goctl. DO NOT EDIT!
// Source: service.proto

package userclient

import (
	"context"

	"go-back/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GroupIdListResponse = user.GroupIdListResponse
	UidRequest          = user.UidRequest

	User interface {
		GetGroupIdList(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*GroupIdListResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetGroupIdList(ctx context.Context, in *UidRequest, opts ...grpc.CallOption) (*GroupIdListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetGroupIdList(ctx, in, opts...)
}
