// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"wechat-backend/service/search/api/internal/handler/search"
	"wechat-backend/service/search/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyAuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: search.SearchHandler(serverCtx),
				},
			}...,
		),
	)
}
