// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"wechat-backend/service/user/rpc/internal/logic"
	"wechat-backend/service/user/rpc/internal/svc"
	"wechat-backend/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 获取所有用户
func (s *UserServer) GetAllUserIdList(ctx context.Context, in *user.Empty) (*user.UIdListResponse, error) {
	l := logic.NewGetAllUserIdListLogic(ctx, s.svcCtx)
	return l.GetAllUserIdList(in)
}

// 获取所有好友
func (s *UserServer) GetFriendIdList(ctx context.Context, in *user.GetFriendIdListRequest) (*user.UIdListResponse, error) {
	l := logic.NewGetFriendIdListLogic(ctx, s.svcCtx)
	return l.GetFriendIdList(in)
}
