// Code generated by goctl. DO NOT EDIT.
package types

type BaseInfo struct {
	Uid       int64  `json:"uid"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Age       int64  `json:"age"`
	Avatar    string `json:"avatar"`
	Email     string `json:"email"`
	Introduce string `json:"introduce"`
}

type UserInfo struct {
	BaseInfo
	LastTime    string `json:"last_time"`
	LastAddress string `json:"last_address"`
}

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string   `json:"token"`
	Data  UserInfo `json:"userinfo"`
}

type UserId struct {
	Uid int64 `json:"uid"`
}

type UserInfoResponse struct {
	Data UserInfo `json:"userinfo"`
}

type UserChatListInfoResponse struct {
	UserChatList []UserChatListInfo `json:"chatlist"`
}

type UserChatListInfo struct {
	Uid      int64  `json:"uid"`
	Avatar   string `json:"avatar"`
	Nickname string `json:"nickname"`
}

type SaveChatListRequest struct {
	Uid              int64            `json:"uid"`
	UserChatListInfo UserChatListInfo `json:"userchatlistinfo"`
}

type FriendInfo struct {
	BaseInfo
}

type FriendListResponse struct {
	FriendList []FriendInfo `json:"friendlist"`
}

type FriendDetailResponse struct {
	BaseInfo
}

type GroupInfo struct {
	Gid        int64  `json:"gid"`
	Uid        int64  `json:"uid"`
	Avatar     string `json:"avatar"`
	Gname      string `json:"gname"`
	Count      string `json:"count"`
	CreateTime string `json:"create_time"`
}

type GroupListResponse struct {
	GroupList []GroupInfo `json:"grouplist"`
}

type GroupId struct {
	Gid int64 `json:"gid"`
}

type GroupDetailResponse struct {
	GroupInfo
	Nickname   string       `json:"nickname"`
	FriendList []FriendInfo `json:"friendlist"`
}
