// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	chatconn "wechat-backend/service/communicate/api/internal/handler/chatconn"
	record "wechat-backend/service/communicate/api/internal/handler/record"
	"wechat-backend/service/communicate/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyAuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: record.RecordListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/record"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyAuthorityMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/chatconn",
					Handler: chatconn.ChatConnHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1"),
	)
}
