// Code generated by goctl. DO NOT EDIT.
package types

type UserDetail struct {
	Username    string `json:"username"`
	Nickname    string `json:"nickname"`
	Age         int64  `json:"age"`
	Avatar      string `json:"avatar"`
	Email       string `json:"email"`
	Introduce   string `json:"introduce"`
	LastTime    string `json:"last_time"`
	LastAddress string `json:"last_address"`
}

type GroupDetail struct {
	Gid        int64  `json:"gid"`
	Uid        int64  `json:"uid"`
	Avatar     string `json:"avatar"`
	Gname      string `json:"gname"`
	Count      string `json:"count"`
	CreateTime string `json:"create_time"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserInfo UserDetail `json:"UserInfo"`
	Token    string     `json:"token"`
}

type UserNameRequest struct {
	Username string `form:"username"`
}

type UidRequest struct {
	Uid int64 `form:"uid"`
}

type UserDetailResponse struct {
	UserInfo UserDetail `json:"userinfo"`
}

type FriendListResponse struct {
	FriendList []UserDetail `json:"friends"`
}

type GroupListResponse struct {
	GroupList []GroupDetail `json:"groups"`
}

type GroupIdRequest struct {
	Gid int64 `form:"gid"`
}

type GroupDetailResponse struct {
	GroupInfo GroupDetail `json:"groupinfo"`
}

type GroupCrewResponse struct {
	Crew []UserDetail `json:"crew"`
}
